version: '3'
  
  
services:
  nginx:
    image: nginx:1.23.2-alpine
    ports:
      - 80:8080
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./nginx/logs:/var/www/backend/logs
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    expose:
      - 8000
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    expose:
      - 5173
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - .env
  db:
    image: postgres:15.1-alpine
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data/
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  adminer:
    image: adminer:4.8.1-standalone
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata:
