# Dockerfile

# pull the official docker image
FROM python:3.11-buster

# set work directory
WORKDIR /app

# set env variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install dependencies
COPY backend .
RUN pip install poetry
RUN poetry config virtualenvs.create false
RUN poetry install